name: GeoCLEWs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - affine>=2.4
  - attrs>=22.1
  - click>=8.1
  - click-plugins>=1.1
  - cligj>=0.7
  - fiona>=1.9
  - gdal>=3.4
  - geojson>=2.5
  - geopandas>=0.14
  - ipykernel>=6.29
  - ipython>=8.20
  - ipywidgets>=8.0
  - jupyterlab>=4.0
  - matplotlib>=3.8
  - numpy>=1.26
  - pandas>=2.2
  - plotly>=5.18
  - pyproj>=3.6
  - pyqt>=5.15
  - rasterio>=1.3
  - requests>=2.31
  - rtree>=1.2
  - scikit-learn>=1.4
  - rasterstats>=0.19
  - scipy>=1.11
  - shapely>=2.0
  - statsmodels>=0.14
  - pip:
      - pyqt5-sip>=12.13
      - pyqtchart>=5.15
      - pyqtwebengine>=5.15
